#Default variables
#Ref:: https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Ubuntu
#
# @Rolind Roy < hello@rolindroy.com >
#----------------------------------------------------------------------------


jenkins_repo_url: deb http://pkg.jenkins.io/debian-stable binary/
jenkins_repo_key: http://pkg.jenkins.io/debian/jenkins-ci.org.key
jenkins_home_path: /var/lib/jenkins
jenkins_init_file: /etc/default/jenkins
jenkins_http_port: 7070
jenkins_url_prefix: ""

jenkins_hostname: localhost
jenkins_jar_location: /opt/jenkins-cli.jar

jenkins_init_changes:
  - {option: "JENKINS_ARGS", value: "--prefix={{ jenkins_url_prefix }}"}
  - {option: "JENKINS_JAVA_OPTIONS", value: "{{ jenkins_java_options }}"}

