
#*******************************************************************************************************************
#This is the Bootstrap project for setting up end-to-end DevOps CI/CD Integration process written by Rolind Roy.
#
#This projects contains bash scripts and ansible playbooks, 
#Docker that can be execute in any Debian based platform such as Ubuntu (14.04, 16.04). 
#It can be integrated "end-to-end" CI/CD Process that starts from setting up environments to Deployed on Web server.  
#
# ---   @author Rolind Roy < hello@rolindroy.com >
#*******************************************************************************************************************

jenkins_repo_url: deb http://pkg.jenkins.io/debian-stable binary/
jenkins_repo_key: http://pkg.jenkins.io/debian/jenkins-ci.org.key
jenkins_home_path: /var/lib/jenkins
jenkins_init_file: /etc/default/jenkins
jenkins_http_port: 7070
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_hostname: localhost
jenkins_jar_location: /opt/jenkins-cli.jar

jenkins_admin_username: admin
jenkins_admin_password: admin@123

jenkins_init_changes:
  - {option: "JENKINS_ARGS", value: "--prefix={{ jenkins_url_prefix }}"}
  - {option: "JENKINS_JAVA_OPTIONS", value: "{{ jenkins_java_options }}"}

jenkins_job_dir_path: /var/lib/jenkins/jobs/
jenkins_job_name: DevOps_Sample_Deployment_Project  
  
jenkins_plugins: []
jenkins_update_plugins: true
jenkins_install_recommended_plugins: true
jenkins_recommended_plugins:
  - "ace-editor"
  - "ant"
  - "antisamy-markup-formatter"
  - "branch-api"
  - "build-timeout"
  - "cloudbees-folder"
  - "credentials"
  - "credentials-binding"
  - "durable-task"
  - "email-ext"
  - "external-monitor-job"
  - "git"
  - "git-client"
  - "github"
  - "github-api"
  - "github-branch-source"
  - "github-organization-folder"
  - "git-server"
  - "gradle"
  - "handlebars"
  - "icon-shim"
  - "javadoc"
  - "jquery-detached"
  - "junit"
  - "ldap"
  - "mailer"
  - "mapdb-api"
  - "matrix-auth"
  - "matrix-project"
  - "momentjs"
  - "pam-auth"
  - "pipeline-build-step"
  - "pipeline-input-step"
  - "pipeline-rest-api"
  - "pipeline-stage-step"
  - "pipeline-stage-view"
  - "plain-credentials"
  - "scm-api"
  - "script-security"
  - "ssh-credentials"
  - "ssh-slaves"
  - "structs"
  - "subversion"
  - "timestamper"
  - "token-macro"
  - "windows-slaves"
  - "workflow-aggregator"
  - "workflow-api"
  - "workflow-basic-steps"
  - "workflow-cps"
  - "workflow-cps-global-lib"
  - "workflow-durable-task-step"
  - "workflow-job"
  - "workflow-multibranch"
  - "workflow-scm-step"
  - "workflow-step-api"
  - "workflow-support"
  - "ws-cleanup"
