---
- name: Updating Jenkins HTTP Port settings.
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^HTTP_PORT='
    line: 'HTTP_PORT={{ jenkins_http_port }}'
  register: jenkins_http_port_fix 
  
# - name: Modify variables in init file
  # lineinfile:
    # dest: "{{ jenkins_init_file }}"
    # insertafter: '^{{ item.option }}='
    # regexp: '^{{ item.option}}=\"\${{ item.option }} '
    # line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
    # state: present
  # with_items:
      # "{{ jenkins_init_changes }}"
  # register: jenkins_init_prefix

# - name: Immediately restart Jenkins on init config changes.
  # service: name=jenkins state=restarted
  # when: jenkins_init_prefix.changed
  
# - name: Create custom init scripts directory.
  # file:
    # path: /var/lib/jenkins/init.groovy.d
    # state: directory
    # owner: jenkins
    # group: jenkins
    # mode: 0775

# - name: Configure Jenkins default users.
  # template:
    # src: basic-security.groovy
    # dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
    # owner: jenkins
    # group: jenkins
    # mode: 0775
  # register: jenkins_users_config

# - name: Immediately restart Jenkins on http or user changes.
  # service: name=jenkins state=restarted
  # when: jenkins_users_config.changed or jenkins_http_config.changed