---
#Configuring Jenkins default Job

- name: Create custom job directory.
  file:
    path: "{{ jenkins_job_dir_path }}/{{ jenkins_job_name }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775

- name: Configure default jenkins job.
  template:
    src: config.xml
    dest: "{{ jenkins_job_dir_path }}/{{ jenkins_job_name }}/config.xml"
    owner: jenkins
    group: jenkins
    mode: 0775
  register: jenkins_job_created

 