---
- name: Updating Jenkins HTTP Port settings.
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^HTTP_PORT='
    line: 'HTTP_PORT={{ jenkins_http_port }}'
  register: jenkins_http_port_fix 
  
- name: Configure jenkins server.
  template:
    src: jenkins_config.xml
    dest: "{{ jenkins_home_path }}/config.xml"
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Immediately restart Jenkins on init config changes.
  shell: service jenkins restart
  ignore_errors: True

- name: Download Plugins.
  get_url:
    url: "{{ jenkins_plugin_download_url }}"
    dest: "{{ workspace }}/{{ plugin_file_name }}.zip"

- name: Installing Plugins.
  unarchive:
    src: "{{ workspace }}/{{ plugin_file_name }}.zip"
    dest: "{{ jenkins_home_path }}"
    copy: no

- name: Setting permission for all plugins
  file:
    path: "{{ jenkins_home_path }}"
    owner: jenkins
    group: jenkins
    recurse: yes
    
- name: Immediately restart Jenkins after installing plugin.
  service: name=jenkins state=restarted
