---
- name: Install {{ type }} Jenkins plugins
  shell: >
    java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/ install-plugin {{ item }} --username {{ jenkins_admin_users.0.username }} --password {{ jenkins_admin_users.0.password }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  failed_when: "install_plugin_results.rc != 0  and install_plugin_results.rc != 255"
  register: install_plugin_results
  with_items: "{{ jenkins_plugins_to_install }}"
  notify: restart jenkins
